### ISSUE TITLE
Multiple Requests

### ISSUE THREAD

**Issue by dave-miller** [FireEngineRed/smartystreets-laravel#1]
Nevermind, I realized laravel is loading it as a service provider, thus if you make 10 requests, it's sending 10 addresses in 1 request, but the package only ever returns the [0] index element.

Also $reqeust is spelled incorrectly at the top of your class, should be '$request'

**Comment by scottconnerly** [comment]
Out of box, yes. But if you build up some structure around addressAddToRequest() addressGetCandidates(), you can get multiple. addressQuickVerify() is the super-simple version. I didn't want to get into assuming I know about how you need to iterate over these, so I left that part out.

Fixed $reqeust to $request. Thanks.
