### ISSUE TITLE
Laravel Service Provider Name

### ISSUE THREAD

**Issue by impeto** [FireEngineRed/smartystreets-laravel#3]
Packagist.org documentation says the name of the service provider is this:
`'FireEngineRed\SmartyStreetsLaravel\SmartyStreetsLaravelServiceProvider'`

It should be this:
`'FireEngineRed\SmartyStreetsLaravel\SmartyStreetsServiceProvider'` (no "Laravel" in the class name)

EDIT: I see that the redme.md on github says the same thing.

**Comment by scottconnerly** [comment]
Resolved
